<?php
/**
 * Template Name: Reach First — how we work
 */
defined( 'ABSPATH' ) || exit;
get_header();
?>
<main id="main-content" tabindex="-1">
    <section class="work-hero section-space" aria-labelledby="work-heading"><div class="site-container work-hero-layout"><div class="work-hero-copy"><p class="eyebrow">How we work</p><h1 id="work-heading">A clear path from <span>problem to progress.</span></h1><p>We begin with the work your business needs to improve, define what success means, test the right-sized approach, and build toward dependable everyday use.</p><div class="detail-actions"><a class="button button-primary" href="#work-phases">See the five phases<svg class="icon"><use href="#w-arrow"/></svg></a><a class="services-page-text-link" href="#engagement-tracks">Compare engagement types<svg class="icon"><use href="#w-arrow"/></svg></a></div></div><aside class="work-route" aria-label="Reach First delivery route"><div class="work-route-head"><span>One connected delivery route</span><strong>5 phases</strong></div><ol><li><span>01</span><strong>Assess</strong><small>Understand the current state</small></li><li><span>02</span><strong>Define</strong><small>Agree on outcomes and scope</small></li><li><span>03</span><strong>Pilot</strong><small>Test the focused approach</small></li><li><span>04</span><strong>Implement</strong><small>Prepare for real-world use</small></li><li><span>05</span><strong>Improve</strong><small>Measure, support, and refine</small></li></ol></aside></div></section>

    <section class="work-principles" aria-label="Our delivery principles"><div class="site-container"><div><svg><use href="#w-map"/></svg><span><strong>Process before platform</strong> Understand the work first</span></div><div><svg><use href="#w-flask"/></svg><span><strong>Focused before broad</strong> Test before scaling</span></div><div><svg><use href="#w-users"/></svg><span><strong>People stay involved</strong> Clear owners and handoffs</span></div></div></section>

    <section id="work-phases" class="work-phases section-space" aria-labelledby="phases-heading"><div class="site-container"><div class="work-section-heading"><div><p class="eyebrow">The delivery model</p><h2 id="phases-heading">Five phases. A decision at every transition.</h2></div><p>Each phase creates something reviewable before more time or budget is committed. The exact activities and deliverables depend on the engagement.</p></div><ol class="work-phase-list">
      <li><div class="work-phase-marker"><span>01</span><svg><use href="#w-map"/></svg></div><div class="work-phase-main"><p class="work-phase-label">Assess</p><h3>Understand the work as it operates today.</h3><p>We examine the business objective, current steps, systems, data, people, pain points, dependencies, and exceptions before recommending a solution.</p><ul><li>Stakeholder and workflow discovery</li><li>Systems, access, and data review</li><li>Opportunity and constraint mapping</li></ul></div><aside><span>Review point</span><strong>Is this the right problem to solve?</strong><small>Typical output: current-state map and opportunity brief</small></aside></li>
      <li><div class="work-phase-marker"><span>02</span><svg><use href="#w-ruler"/></svg></div><div class="work-phase-main"><p class="work-phase-label">Define</p><h3>Turn the opportunity into an agreed plan.</h3><p>We establish the intended outcome, baseline, scope, responsibilities, measures, risks, and what is intentionally outside the first release.</p><ul><li>Success measures and acceptance criteria</li><li>Solution or campaign approach</li><li>Roadmap, roles, and decision boundaries</li></ul></div><aside><span>Review point</span><strong>Is the scope useful, feasible, and understood?</strong><small>Typical output: proposed approach and scoped roadmap</small></aside></li>
      <li><div class="work-phase-marker"><span>03</span><svg><use href="#w-flask"/></svg></div><div class="work-phase-main"><p class="work-phase-label">Pilot</p><h3>Test the riskiest assumptions at a useful scale.</h3><p>We create a focused version, test normal and exception paths, gather feedback, and compare what happened with the agreed evaluation criteria.</p><ul><li>Focused build or initial campaign</li><li>Functional, quality, and exception testing</li><li>User or audience feedback review</li></ul></div><aside><span>Review point</span><strong>What did we learn, and should we proceed?</strong><small>Typical output: pilot findings and recommended changes</small></aside></li>
      <li><div class="work-phase-marker"><span>04</span><svg><use href="#w-blocks"/></svg></div><div class="work-phase-main"><p class="work-phase-label">Implement</p><h3>Prepare the work for dependable use.</h3><p>We complete the agreed configuration, integrations, content, testing, documentation, approvals, training, and rollout activities.</p><ul><li>Production implementation and quality assurance</li><li>Permissions, handoffs, and escalation paths</li><li>Documentation, training, and launch readiness</li></ul></div><aside><span>Review point</span><strong>Are the people, process, and system ready?</strong><small>Typical output: approved launch and operating guidance</small></aside></li>
      <li><div class="work-phase-marker"><span>05</span><svg><use href="#w-refresh"/></svg></div><div class="work-phase-main"><p class="work-phase-label">Improve</p><h3>Measure what matters and refine responsibly.</h3><p>After launch, agreed monitoring and support reveal performance, failures, new requirements, and the next improvements worth prioritizing.</p><ul><li>Performance and issue monitoring</li><li>Support, maintenance, and optimization</li><li>Improvement backlog and change decisions</li></ul></div><aside><span>Review point</span><strong>What should be maintained, changed, or expanded?</strong><small>Typical output: performance review and prioritized next steps</small></aside></li>
    </ol></div></section>

    <section id="engagement-tracks" class="work-tracks section-space" aria-labelledby="tracks-heading"><div class="site-container"><div class="work-section-heading work-section-heading-light"><div><p class="eyebrow">Different work, shared discipline</p><h2 id="tracks-heading">The model adapts to the engagement.</h2></div><p>Automation and marketing do not produce the same deliverables. Both still need discovery, a defined strategy, purposeful execution, measurement, and iteration.</p></div><div class="work-track-grid"><article><div><span>Automation &amp; technology</span><svg><use href="#w-blocks"/></svg></div><h3>From workflow friction to supported implementation.</h3><ol><li><span>Assess</span><p>Workflow, systems, data, permissions, and exceptions</p></li><li><span>Define</span><p>Use case, success criteria, architecture, and ownership</p></li><li><span>Pilot</span><p>Focused automation with human review and testing</p></li><li><span>Implement</span><p>Integrations, safeguards, documentation, and training</p></li><li><span>Improve</span><p>Monitoring, maintenance, and controlled expansion</p></li></ol><a href="<?php echo esc_url( reachfirst_page_url( 'services' ) . '' ); ?>">Explore automation services<svg><use href="#w-arrow"/></svg></a></article><article><div><span>Digital marketing</span><svg><use href="#w-refresh"/></svg></div><h3>From market understanding to measurable optimization.</h3><ol><li><span>Assess</span><p>Brand, audience, market, competitors, and current performance</p></li><li><span>Define</span><p>Positioning, targeting, channel strategy, and measures</p></li><li><span>Pilot</span><p>Focused campaign, content, or experience improvements</p></li><li><span>Implement</span><p>Creative, media, website, search, and campaign delivery</p></li><li><span>Improve</span><p>Measure, analyze, optimize, and refine the mix</p></li></ol><a href="<?php echo esc_url( reachfirst_page_url( 'digital-marketing-services' ) . '' ); ?>">Explore marketing services<svg><use href="#w-arrow"/></svg></a></article></div></div></section>

    <section class="work-collaboration section-space" aria-labelledby="collaboration-heading"><div class="site-container"><div class="work-section-heading"><div><p class="eyebrow">Working together</p><h2 id="collaboration-heading">Clear responsibilities keep the work moving.</h2></div><p>A successful engagement needs active participation on both sides. We confirm project-specific roles during planning.</p></div><div class="work-collaboration-grid"><article><span>What you can expect from Reach First</span><ul><li><svg><use href="#w-check"/></svg><div><strong>A named direction</strong><p>Clear objectives, scope, assumptions, and next decisions.</p></div></li><li><svg><use href="#w-check"/></svg><div><strong>Visible progress</strong><p>Reviewable work, findings, and issues at agreed checkpoints.</p></div></li><li><svg><use href="#w-check"/></svg><div><strong>Plain-language trade-offs</strong><p>Options and limitations explained before important choices.</p></div></li><li><svg><use href="#w-check"/></svg><div><strong>Operational thinking</strong><p>Attention to adoption, handoffs, documentation, and support.</p></div></li></ul></article><article><span>What we need from your team</span><ul><li><svg><use href="#w-users"/></svg><div><strong>An accountable owner</strong><p>Someone able to coordinate access, feedback, and decisions.</p></div></li><li><svg><use href="#w-users"/></svg><div><strong>Access to the real process</strong><p>People, tools, examples, data context, and known exceptions.</p></div></li><li><svg><use href="#w-users"/></svg><div><strong>Timely review</strong><p>Feedback and approvals from the right stakeholders.</p></div></li><li><svg><use href="#w-users"/></svg><div><strong>Change participation</strong><p>Staff involvement in testing, training, and adoption.</p></div></li></ul></article></div></div></section>

    <section class="work-guardrails section-space" aria-labelledby="guardrails-heading"><div class="site-container work-guardrails-layout"><div><p class="eyebrow">Built into the lifecycle</p><h2 id="guardrails-heading">Risk, oversight, and measurement are not final-step checkboxes.</h2><p>For AI-enabled work, we treat context, ownership, testing, human review, and ongoing monitoring as cross-cutting concerns. The appropriate controls depend on the use case, impact, data, systems, and organizational requirements.</p><small>This describes our delivery approach, not a claim of certification or universal regulatory compliance.</small></div><div class="work-guardrail-board"><div><svg><use href="#w-shield"/></svg><span>Govern</span><p>Owners, responsibilities, access, and escalation</p></div><div><span>Map</span><p>Context, intended use, affected people, and risks</p></div><div><span>Measure</span><p>Tests, evidence, limits, and agreed performance signals</p></div><div><span>Manage</span><p>Priorities, controls, monitoring, and change decisions</p></div></div></div></section>

    <section class="work-timing section-space" aria-labelledby="timing-heading"><div class="site-container"><div class="work-section-heading"><div><p class="eyebrow">Planning expectations</p><h2 id="timing-heading">What shapes scope and timing?</h2></div><p>We establish a project plan after assessment because duration depends on the actual operating environment, not a generic package.</p></div><ul class="work-timing-grid"><li><span>01</span><strong>Process complexity</strong><p>Number of steps, variants, exceptions, and stakeholders.</p></li><li><span>02</span><strong>System access</strong><p>Available integrations, permissions, vendors, and environments.</p></li><li><span>03</span><strong>Data readiness</strong><p>Quality, structure, volume, ownership, and permitted use.</p></li><li><span>04</span><strong>Review cycles</strong><p>Decision-makers, feedback speed, approvals, and dependencies.</p></li><li><span>05</span><strong>Change impact</strong><p>Training, documentation, rollout, and operational adoption.</p></li></ul></div></section>

    <section class="detail-faq work-faq section-space" aria-labelledby="work-faq-heading"><div class="site-container detail-faq-layout"><div><p class="eyebrow">Before we begin</p><h2 id="work-faq-heading">Practical questions about the engagement.</h2><p>These answers set general expectations. The proposal and project plan define the specific arrangement.</p></div><div class="detail-faq-list"><details open><summary>Do all projects use all five phases?<svg><use href="#w-arrow"/></svg></summary><p>The thinking applies across engagements, but the depth and deliverables vary. A focused assessment may end with a roadmap, while a larger engagement may continue through implementation and ongoing improvement.</p></details><details><summary>How do you decide what to pilot?<svg><use href="#w-arrow"/></svg></summary><p>We look for a use case or campaign that is valuable enough to learn from, bounded enough to evaluate, and suitable for testing without unnecessary disruption.</p></details><details><summary>Can you work with our existing systems and partners?<svg><use href="#w-arrow"/></svg></summary><p>Often, subject to the available integrations, permissions, vendor constraints, security requirements, responsibilities, and the agreed scope.</p></details><details><summary>When will we know the timeline and cost?<svg><use href="#w-arrow"/></svg></summary><p>After we understand the workflow, intended outcome, systems, data, access, dependencies, and support needs. We then propose a scope, plan, assumptions, and commercial arrangement for review.</p></details><details><summary>What happens if the pilot does not support the original idea?<svg><use href="#w-arrow"/></svg></summary><p>That is useful evidence. We review why, then recommend whether to adjust the approach, address a prerequisite, test a different direction, or stop rather than scale an unsuitable solution.</p></details></div></div></section>

    <section class="about-cta section-space"><div class="site-container"><div class="about-cta-panel"><div><p class="eyebrow">Start with the current state</p><h2>What work is slowing your team down or limiting growth?</h2><p>Bring the process, problem, available evidence, systems, and outcome you want to improve. We&rsquo;ll help define a practical next step.</p></div><a class="button about-cta-button" href="<?php echo esc_url( reachfirst_page_url( 'book-consultation' ) . '' ); ?>">Request a consultation by email<svg class="icon"><use href="#w-arrow-up"/></svg></a></div></div></section>
  </main>
<?php get_footer(); ?>
