<?php
/**
 * Template Name: Reach First — ai voice agents
 */
defined( 'ABSPATH' ) || exit;
get_header();
?>
<main id="main-content" tabindex="-1"><section class="detail-hero section-space"><div class="site-container"><nav class="detail-breadcrumb"><a href="<?php echo esc_url( reachfirst_page_url( 'services' ) . '' ); ?>">Services</a><svg><use href="#d-arrow"/></svg><span>AI Voice Agents</span></nav><div class="detail-hero-layout"><div class="detail-hero-copy"><p class="eyebrow">Structure routine inbound calls</p><h1>AI Voice <span>Agents</span></h1><p>Handle defined enquiry and appointment workflows by phone, capture useful details, and route callers to staff when a conversation needs human attention.</p><div class="detail-actions"><a class="button button-primary" href="<?php echo esc_url( reachfirst_page_url( 'book-consultation' ) . '' ); ?>">Discuss a voice workflow<svg class="icon"><use href="#d-arrow-up"/></svg></a><a class="services-page-text-link" href="#what-includes">What this can include<svg class="icon"><use href="#d-arrow"/></svg></a></div></div><div class="detail-visual" aria-label="A voice workflow connects callers, information, scheduling, and staff"><div class="detail-visual-core"><svg><use href="#d-service"/></svg><span>Voice workflow</span></div><span class="detail-chip detail-chip-one">Caller</span><span class="detail-chip detail-chip-two">Information</span><span class="detail-chip detail-chip-three">Scheduling</span><span class="detail-chip detail-chip-four">Staff</span></div></div></div></section>
<section class="detail-fit section-space"><div class="site-container detail-fit-layout"><div class="detail-fit-intro"><p class="eyebrow">Where it can help</p><h2>Useful when routine calls need consistent intake and routing.</h2><p>The service is designed around defined call types, not open-ended replacement for staff.</p></div><ul class="detail-signals"><li><span>01</span><p>Routine calls interrupt staff or go unanswered during busy periods.</p></li><li><span>02</span><p>Appointment or service requests follow a consistent intake pattern.</p></li><li><span>03</span><p>Call details need to reach the right person in a usable format.</p></li><li><span>04</span><p>Callers need a clear path to staff for exceptions or sensitive issues.</p></li></ul></div></section>
<section id="what-includes" class="detail-scope section-space"><div class="site-container"><div class="detail-section-intro"><p class="eyebrow">What this can include</p><h2>Defined conversations with clear outcomes and handoffs.</h2><p>Capabilities depend on telephony, scheduling, information, consent, and integration requirements.</p></div><div class="detail-scope-grid"><article class="detail-scope-card"><span>01</span><h3>Enquiry intake</h3><p>Collect agreed details for eligible request types.</p></article><article class="detail-scope-card"><span>02</span><h3>Appointment requests</h3><p>Check or capture scheduling preferences based on connected capabilities.</p></article><article class="detail-scope-card"><span>03</span><h3>Routing and escalation</h3><p>Transfer or queue calls when staff involvement is required.</p></article><article class="detail-scope-card"><span>04</span><h3>Summaries and follow-up</h3><p>Prepare structured call notes, notifications, or review-ready next steps.</p></article></div></div></section>
<section class="detail-example section-space"><div class="site-container detail-example-layout"><div class="detail-section-intro"><p class="eyebrow">Illustrative call path</p><h2>From a routine request to a staff-ready summary.</h2><p>This fictional sequence is not a live telephony demonstration.</p></div><div class="detail-example-flow"><p class="detail-example-note">Example only — recording, consent, and routing requirements vary.</p><ol><li><span>01</span><div><h3>Purpose identified</h3><p>The caller selects or describes an eligible request.</p></div></li><li><span>02</span><div><h3>Details collected</h3><p>The voice agent asks the approved intake questions.</p></div></li><li><span>03</span><div><h3>Boundary checked</h3><p>The request is assessed against routing and escalation rules.</p></div></li><li><span>04</span><div><h3>Outcome prepared</h3><p>A handoff, request, or summary is created as agreed.</p></div></li></ol></div></div></section>
<section class="detail-process section-space"><div class="site-container"><div class="detail-process-intro"><p class="eyebrow">How we build it</p><h2>Design the conversation before connecting the phone line.</h2><p>Testing covers realistic phrasing, interruptions, uncertainty, and escalation.</p></div><ol class="detail-process-grid"><li><span>01</span><h3>Define</h3><p>Agree call types, disclosures, questions, and exclusions.</p></li><li><span>02</span><h3>Design</h3><p>Map conversation paths, integrations, and handoffs.</p></li><li><span>03</span><h3>Test</h3><p>Evaluate representative and difficult call scenarios.</p></li><li><span>04</span><h3>Operate</h3><p>Monitor behavior and maintain scripts and connections.</p></li></ol></div></section>
<section class="detail-guardrails section-space"><div class="site-container detail-guardrails-layout"><div><p class="eyebrow">Caller trust</p><h2>Disclosure, consent, and human handoff belong in the design.</h2></div><div class="detail-guardrails-copy"><p>Callers should understand that they are interacting with an AI system. Recording, transcription, consent, and retention requirements must be assessed for the intended use and jurisdictions.</p><p>Emergency, sensitive, low-confidence, and out-of-scope situations need clear routing behavior.</p></div></div></section>
<section class="detail-related section-space"><div class="site-container"><div class="detail-section-intro"><p class="eyebrow">Related services</p><h2>Connect calls to the wider customer workflow.</h2></div><div class="detail-related-grid"><a class="detail-related-card" href="<?php echo esc_url( reachfirst_page_url( 'ai-agents-customer-support' ) . '' ); ?>"><span>Assist</span><h3>AI Agents &amp; Customer Support</h3><p>Use approved knowledge and escalation across support channels.</p><svg><use href="#d-arrow"/></svg></a><a class="detail-related-card" href="<?php echo esc_url( reachfirst_page_url( 'sales-crm-automation' ) . '' ); ?>"><span>Coordinate</span><h3>Sales &amp; CRM Automation</h3><p>Route call outcomes into follow-up and CRM processes.</p><svg><use href="#d-arrow"/></svg></a></div></div></section>
<section class="detail-faq section-space"><div class="site-container detail-faq-layout"><div><p class="eyebrow">Voice questions</p><h2>Before adding an AI voice workflow.</h2></div><div class="detail-faq-list"><details open><summary>Can callers reach a person?<svg><use href="#d-chevron"/></svg></summary><p>Staff routing and escalation can be designed for the agreed call types, hours, and operational setup.</p></details><details><summary>Can it book appointments?<svg><use href="#d-chevron"/></svg></summary><p>Potentially, depending on scheduling-system access, availability rules, permissions, and the level of review required.</p></details><details><summary>Are calls recorded?<svg><use href="#d-chevron"/></svg></summary><p>Recording and transcription are project decisions that require appropriate disclosure, consent, retention, and privacy review.</p></details></div></div></section>
<section class="about-cta section-space"><div class="site-container"><div class="about-cta-panel"><div><p class="eyebrow">Start with one call type</p><h2>Which routine calls should we examine?</h2><p>We’ll discuss call volume, questions, systems, staff routing, and compliance considerations.</p><p class="detail-cta-note">Helpful to bring: sample calls, scripts, scheduling rules, and escalation paths.</p></div><a class="button about-cta-button" href="<?php echo esc_url( reachfirst_page_url( 'book-consultation' ) . '' ); ?>">Request a consultation by email<svg class="icon"><use href="#d-arrow-up"/></svg></a></div></div></section></main>
<?php get_footer(); ?>
