<?php
/**
 * Template Name: Reach First — managed ai automation support
 */
defined( 'ABSPATH' ) || exit;
get_header();
?>
<main id="main-content" tabindex="-1"><section class="detail-hero section-space"><div class="site-container"><nav class="detail-breadcrumb"><a href="<?php echo esc_url( reachfirst_page_url( 'services' ) . '' ); ?>">Services</a><svg><use href="#d-arrow"/></svg><span>Managed AI &amp; Automation Support</span></nav><div class="detail-hero-layout"><div class="detail-hero-copy"><p class="eyebrow">Support beyond launch</p><h1>Managed AI &amp; <span>Automation Support</span></h1><p>Keep agreed implementations maintained, monitored, documented, and useful as your workflows, systems, information, and team needs change.</p><div class="detail-actions"><a class="button button-primary" href="<?php echo esc_url( reachfirst_page_url( 'book-consultation' ) . '' ); ?>">Discuss ongoing support<svg class="icon"><use href="#d-arrow-up"/></svg></a><a class="services-page-text-link" href="#what-includes">What this can include<svg class="icon"><use href="#d-arrow"/></svg></a></div></div><div class="detail-visual" aria-label="Managed support connects monitoring, maintenance, team help, and improvements"><div class="detail-visual-core"><svg><use href="#d-service"/></svg><span>Managed support</span></div><span class="detail-chip detail-chip-one">Monitor</span><span class="detail-chip detail-chip-two">Maintain</span><span class="detail-chip detail-chip-three">Support</span><span class="detail-chip detail-chip-four">Improve</span></div></div></div></section>
<section class="detail-fit section-space"><div class="site-container detail-fit-layout"><div class="detail-fit-intro"><p class="eyebrow">Where it can help</p><h2>Useful when an automation has become part of everyday operations.</h2><p>Support terms are matched to the implementation and the level of operational responsibility agreed.</p></div><ul class="detail-signals"><li><span>01</span><p>Connected systems or APIs may change over time.</p></li><li><span>02</span><p>Knowledge, rules, prompts, or routing need controlled updates.</p></li><li><span>03</span><p>Staff need a clear route for questions, issues, and exceptions.</p></li><li><span>04</span><p>Performance and recurring failure patterns need review.</p></li></ul></div></section>
<section id="what-includes" class="detail-scope section-space"><div class="site-container"><div class="detail-section-intro"><p class="eyebrow">What this can include</p><h2>Defined operational care for the agreed implementation.</h2><p>The support model depends on solution ownership, hosting, criticality, vendors, and service expectations.</p></div><div class="detail-scope-grid"><article class="detail-scope-card"><span>01</span><h3>Monitoring and issue review</h3><p>Observe agreed signals, investigate reported problems, and track recurring patterns.</p></article><article class="detail-scope-card"><span>02</span><h3>Maintenance</h3><p>Update integrations, configurations, knowledge, or components within the agreed scope.</p></article><article class="detail-scope-card"><span>03</span><h3>Team support</h3><p>Provide a defined route for questions, operational guidance, and documented exceptions.</p></article><article class="detail-scope-card"><span>04</span><h3>Planned improvements</h3><p>Review usage and feedback to prioritize appropriate refinements.</p></article></div></div></section>
<section class="detail-example section-space"><div class="site-container detail-example-layout"><div class="detail-section-intro"><p class="eyebrow">Illustrative support cycle</p><h2>From operational signal to a controlled improvement.</h2><p>The exact response model and service levels are agreed for the project.</p></div><div class="detail-example-flow"><p class="detail-example-note">Example only — not a universal support commitment.</p><ol><li><span>01</span><div><h3>Signal received</h3><p>A monitor, user, or owner reports an issue or pattern.</p></div></li><li><span>02</span><div><h3>Impact assessed</h3><p>The behavior, scope, cause, and priority are reviewed.</p></div></li><li><span>03</span><div><h3>Change prepared</h3><p>A fix, update, or documented workaround is tested.</p></div></li><li><span>04</span><div><h3>Release and learn</h3><p>The change is applied as agreed and the record is updated.</p></div></li></ol></div></div></section>
<section class="detail-process section-space"><div class="site-container"><div class="detail-process-intro"><p class="eyebrow">How support works</p><h2>Clear ownership, channels, priorities, and change control.</h2><p>We define what is supported and how operational requests move from report to resolution.</p></div><ol class="detail-process-grid"><li><span>01</span><h3>Baseline</h3><p>Document the implementation, owners, dependencies, and known risks.</p></li><li><span>02</span><h3>Operate</h3><p>Use agreed monitoring, reporting, and support channels.</p></li><li><span>03</span><h3>Maintain</h3><p>Test and apply scoped fixes or updates.</p></li><li><span>04</span><h3>Improve</h3><p>Review patterns and prioritize planned changes.</p></li></ol></div></section>
<section class="detail-guardrails section-space"><div class="site-container detail-guardrails-layout"><div><p class="eyebrow">Support boundaries</p><h2>Operational responsibility needs to be explicit.</h2></div><div class="detail-guardrails-copy"><p>Support scope, service windows, response targets, monitoring, hosting, vendor dependencies, security responsibilities, and change approval are agreed for the implementation.</p><p>Managed support does not remove the client’s ownership of business policy, risk decisions, source information, or staff responsibilities.</p></div></div></section>
<section class="detail-related section-space"><div class="site-container"><div class="detail-section-intro"><p class="eyebrow">Related services</p><h2>Support what has been planned and built.</h2></div><div class="detail-related-grid"><a class="detail-related-card" href="<?php echo esc_url( reachfirst_page_url( 'business-workflow-automation' ) . '' ); ?>"><span>Automate</span><h3>Business Workflow Automation</h3><p>Design and implement connected operational workflows.</p><svg><use href="#d-arrow"/></svg></a><a class="detail-related-card" href="<?php echo esc_url( reachfirst_page_url( 'custom-ai-applications-integrations' ) . '' ); ?>"><span>Build &amp; connect</span><h3>Custom AI Applications &amp; Integrations</h3><p>Create tailored tools and system connections.</p><svg><use href="#d-arrow"/></svg></a></div></div></section>
<section class="detail-faq section-space"><div class="site-container detail-faq-layout"><div><p class="eyebrow">Support questions</p><h2>Before agreeing an ongoing plan.</h2></div><div class="detail-faq-list"><details open><summary>What is covered by managed support?<svg><use href="#d-chevron"/></svg></summary><p>Coverage is defined for each implementation and may include monitoring, maintenance, updates, documentation, staff support, and agreed improvements.</p></details><details><summary>Do you support systems built by others?<svg><use href="#d-chevron"/></svg></summary><p>Potentially, after a technical and operational assessment establishes the system condition, documentation, access, dependencies, and feasible responsibilities.</p></details><details><summary>Are response times fixed?<svg><use href="#d-chevron"/></svg></summary><p>Response targets and service windows are defined in the agreed support terms; they are not assumed to be the same for every implementation.</p></details></div></div></section>
<section class="about-cta section-space"><div class="site-container"><div class="about-cta-panel"><div><p class="eyebrow">Plan for ongoing use</p><h2>What does your automation need after launch?</h2><p>We’ll discuss the implementation, dependencies, owners, current issues, and level of support required.</p><p class="detail-cta-note">Helpful to bring: architecture notes, vendor list, access model, issue history, and current support responsibilities.</p></div><a class="button about-cta-button" href="<?php echo esc_url( reachfirst_page_url( 'book-consultation' ) . '' ); ?>">Book AI Consultation<svg class="icon"><use href="#d-arrow-up"/></svg></a></div></div></section></main>
<?php get_footer(); ?>
