<?php
/**
 * Template Name: Reach First — action towing case study
 */
defined( 'ABSPATH' ) || exit;
get_header();
?>
<main id="main-content" tabindex="-1" class="case-detail-page">
    <section class="at-hero section-space" aria-labelledby="at-title"><div class="site-container"><a class="at-back" href="<?php echo esc_url( reachfirst_page_url( 'case-studies' ) . '' ); ?>"><svg><use href="#c-arrow"/></svg> All case studies</a><div class="at-hero-copy" data-case-reveal><img class="at-client-logo" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-logo.svg' ) . '' ); ?>" width="220" height="78" alt="Action Towing"><p class="eyebrow">Action Towing · Edmonton, Alberta</p><h1 id="at-title"><span class="at-title-line at-title-primary">A digital experience built for the moment</span><span class="at-title-line at-title-accent">help is needed.</span></h1><p class="at-lede">A responsive website experience that brings a broad towing operation into one clear, service-led journey—from first visit to the right next action.</p><ul class="at-tags"><li>Website Design</li><li>Website Development</li><li>Responsive UX</li></ul></div><div class="at-hero-stage" data-case-reveal><div class="at-hero-route" aria-hidden="true"><svg viewBox="0 0 1200 660" preserveAspectRatio="none"><path d="M40 520C190 520 190 112 410 112S610 555 835 555 955 206 1160 206"/><path d="M92 610C245 610 280 382 500 382S740 92 1110 92"/></svg><i class="route-point point-one"></i><i class="route-point point-two"></i><i class="route-point point-three"></i></div><div class="at-hero-index" aria-hidden="true"><span>Case study · 01</span><small>Website experience</small></div><div class="at-browser at-browser-hero"><div class="at-browser-bar"><i></i><i></i><i></i><span>actiontowingservice.ca</span></div><div class="at-site-hero"><div class="at-site-nav"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-logo.svg' ) . '' ); ?>" alt=""><span>Services</span><span>About</span><b>Call 780-340-0999</b></div><div class="at-site-message"><small>EDMONTON · 24/7</small><strong>Help on the road,<br>when it matters.</strong><span>Standard, heavy-duty and commercial towing with roadside assistance.</span><b>Request towing</b></div></div></div><div class="at-hero-phone" aria-hidden="true"><div class="at-hero-phone-speaker"></div><div class="at-hero-phone-screen"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-logo.svg' ) . '' ); ?>" alt=""><span>EDMONTON · 24/7</span><strong>Help is one tap away.</strong><small>Responsive roadside experience</small><b>Call now</b></div></div><div class="at-stage-note one"><span>01</span><div><strong>24/7 access</strong><small>Clear action at first view</small></div></div><div class="at-stage-note two"><span>02</span><div><strong>Responsive by design</strong><small>One journey across devices</small></div></div><div class="at-stage-note three"><span>03</span><div><strong>Service-led structure</strong><small>Every route stays clear</small></div></div></div></div></section>

    <section class="at-overview section-space" aria-labelledby="at-overview-title"><div class="site-container at-overview-grid"><div data-case-reveal><p class="eyebrow">Project overview</p><h2 id="at-overview-title">A service-first platform for a business that is always moving.</h2></div><div class="at-overview-intro" data-case-reveal><p>Action Towing provides standard, heavy-duty and commercial towing, vehicle recovery and roadside assistance in Edmonton and surrounding communities. The experience organizes those services around the decisions a visitor needs to make quickly.</p><a class="services-page-text-link" href="https://www.actiontowingservice.ca/" target="_blank" rel="noopener noreferrer">Visit the website<svg class="icon"><use href="#c-arrow-up"/></svg></a></div><dl class="at-project-facts" data-case-reveal><div><dt>Client</dt><dd>Action Towing</dd></div><div><dt>Industry</dt><dd>Towing &amp; roadside assistance</dd></div><div><dt>Location</dt><dd>Edmonton, Alberta</dd></div><div><dt>Project type</dt><dd>Responsive marketing website</dd></div><div><dt>Services</dt><dd>Design, development &amp; responsive UX</dd></div><div><dt>Website</dt><dd>actiontowingservice.ca</dd></div></dl></div></section>

    <section class="at-context section-space" aria-labelledby="at-context-title"><div class="site-container at-context-grid"><div class="at-sticky-copy" data-case-reveal><p class="eyebrow">Project context</p><h2 id="at-context-title">Make a complex service offering feel immediate.</h2><p>The current experience has to serve urgent roadside visitors and people planning commercial or heavy-duty support—without making either audience work through unnecessary complexity.</p><small>Detailed starting-point documentation and historic performance data remain pending client approval.</small></div><ol class="at-priority-list"><li data-case-reveal><span>01</span><div><h3>Clarify a broad service catalogue</h3><p>Standard towing, heavy-duty vehicles, recovery, commercial fleets and roadside assistance each need a clear route.</p></div></li><li data-case-reveal><span>02</span><div><h3>Prioritize the urgent action</h3><p>Phone and towing-request pathways stay visible for visitors who need help now.</p></div></li><li data-case-reveal><span>03</span><div><h3>Build confidence quickly</h3><p>Fleet imagery, service detail, operating process and coverage information support informed decisions.</p></div></li><li data-case-reveal><span>04</span><div><h3>Keep mobile friction low</h3><p>The core service and contact journey remains direct on the device most likely to be used roadside.</p></div></li></ol></div></section>

    <section class="at-desktop-showcase section-space" aria-labelledby="at-desktop-title"><div class="site-container"><div class="at-centered-intro" data-case-reveal><p class="eyebrow">Desktop experience</p><h2 id="at-desktop-title">Every essential route stays visible.</h2><p>The composition balances emergency access with enough depth for commercial, fleet and heavy-duty visitors.</p></div><div class="at-annotated" data-case-reveal><div class="at-browser at-browser-large"><div class="at-browser-bar"><i></i><i></i><i></i><span>actiontowingservice.ca</span></div><div class="at-site-hero wide"><div class="at-site-nav"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-logo.svg' ) . '' ); ?>" alt=""><span>Towing Services</span><span>Roadside</span><span>Service Areas</span><b>Call now</b></div><div class="at-site-message"><small>24/7 TOWING IN EDMONTON</small><strong>Ready for the road.<br>Ready when you call.</strong><span>Support for personal vehicles, commercial fleets and heavy equipment.</span><b>Get help now</b></div></div><div class="at-mini-services"><span>Standard towing</span><span>Heavy-duty towing</span><span>Commercial towing</span><span>Roadside assistance</span></div></div><div class="at-callout a">01 · Emergency CTA</div><div class="at-callout b">02 · Service discovery</div><div class="at-callout c">03 · 24/7 messaging</div><div class="at-callout d">04 · Clear categories</div></div></div></section>

    <section class="at-mobile section-space" aria-labelledby="at-mobile-title"><div class="site-container at-mobile-grid"><div class="at-mobile-copy" data-case-reveal><p class="eyebrow">Mobile experience</p><h2 id="at-mobile-title">The shortest path to assistance.</h2><p>Compact navigation, persistent contact cues and concise service choices turn a content-rich site into a calm, readable mobile journey.</p><ul><li><svg><use href="#c-phone"/></svg>Tap-ready phone action</li><li><svg><use href="#c-check"/></svg>Scannable service routes</li><li><svg><use href="#c-map"/></svg>Visible coverage information</li></ul></div><div class="at-phone-stage" data-case-reveal><div class="at-phone back"><div class="at-phone-top"></div><div class="at-phone-screen services"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-logo.svg' ) . '' ); ?>" alt=""><small>OUR SERVICES</small><strong>Find the right tow.</strong><span>Standard towing</span><span>Heavy-duty towing</span><span>Roadside assistance</span></div></div><div class="at-phone front"><div class="at-phone-top"></div><div class="at-phone-screen home"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-logo.svg' ) . '' ); ?>" alt=""><div><small>EDMONTON · 24/7</small><strong>We’re ready<br>when you call.</strong><b>Call 780-340-0999</b></div></div></div><div class="at-mobile-label">Designed for the roadside moment</div></div></div></section>

    <section class="at-ui section-space" aria-labelledby="at-ui-title"><div class="site-container"><div class="case-section-heading" data-case-reveal><div><p class="eyebrow">Interface system</p><h2 id="at-ui-title">A practical visual language with purpose.</h2></div><p>Action blue, direct controls and modular service components reinforce the character of the live experience.</p></div><div class="at-ui-board" data-case-reveal><div class="at-ui-colors"><p>Core palette</p><div><span style="--swatch:#1e4db7">#1E4DB7</span><span style="--swatch:#101010">#101010</span><span style="--swatch:#f0f4ff">#F0F4FF</span><span style="--swatch:#fff">#FFFFFF</span></div></div><div class="at-ui-type"><small>DISPLAY / MANROPE</small><strong>Ready when<br>you call.</strong><span>Clear language for high-intent moments.</span></div><div class="at-ui-controls"><p>Actions &amp; components</p><button>Request towing <svg><use href="#c-arrow-up"/></svg></button><button class="outline"><svg><use href="#c-phone"/></svg> 780-340-0999</button><div><svg><use href="#c-check"/></svg><span><b>Heavy-duty towing</b><small>Equipment for larger vehicles</small></span></div></div></div></div></section>

    <section class="at-breakdown section-space" aria-labelledby="at-breakdown-title"><div class="site-container"><div class="at-centered-intro" data-case-reveal><p class="eyebrow">Experience breakdown</p><h2 id="at-breakdown-title">Designed around real service decisions.</h2></div>
      <article class="at-feature"><div class="at-feature-image" data-case-reveal><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-fleet.webp' ) . '' ); ?>" loading="lazy" alt="Action Towing service truck"><div><small>Service discovery</small><b>Standard · Heavy duty · Commercial · Roadside</b></div></div><div class="at-feature-copy" data-case-reveal><span>01</span><h3>Service discovery</h3><p>Visitors can distinguish everyday towing from specialized recovery, fleet and heavy-duty needs without losing the main contact path.</p></div></article>
      <article class="at-feature reverse"><div class="at-feature-image" data-case-reveal><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-heavy.webp' ) . '' ); ?>" loading="lazy" alt="Action Towing heavy-duty tow truck"><div><small>Emergency conversion</small><b>One prominent phone route</b></div></div><div class="at-feature-copy" data-case-reveal><span>02</span><h3>Emergency conversion</h3><p>Phone-led actions and 24/7 messaging are treated as functional navigation—not decorative marketing copy.</p></div></article>
      <article class="at-feature"><div class="at-feature-image" data-case-reveal><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-commercial.webp' ) . '' ); ?>" loading="lazy" alt="Action Towing commercial fleet towing"><div><small>Trust &amp; capability</small><b>Real fleet imagery supports the service story</b></div></div><div class="at-feature-copy" data-case-reveal><span>03</span><h3>Trust and credibility</h3><p>Real fleet photography, operating steps and specific vehicle capabilities give visitors concrete information to assess fit.</p></div></article>
      <article class="at-feature reverse"><div class="at-feature-image" data-case-reveal><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-service-area.webp' ) . '' ); ?>" loading="lazy" alt="Action Towing truck serving Edmonton"><div><small>Service areas</small><b>Edmonton and nearby communities</b></div></div><div class="at-feature-copy" data-case-reveal><span>04</span><h3>Local service visibility</h3><p>Edmonton coverage is supported by clearly named surrounding communities, helping visitors understand where assistance is available.</p></div></article>
    </div></section>

    <section class="at-results section-space" aria-labelledby="at-results-title"><div class="site-container"><div class="at-results-heading" data-case-reveal><div><p class="eyebrow">Measurement framework</p><h2 id="at-results-title">Built for verified results—not invented ones.</h2></div><p>These modules are ready for approved project data. Until a reporting period and source are confirmed, no performance number is presented.</p></div><div class="at-results-grid"><article data-case-reveal><strong>—</strong><span>Organic visibility</span><small>Verified data pending</small></article><article data-case-reveal><strong>—</strong><span>Qualified calls</span><small>Verified data pending</small></article><article data-case-reveal><strong>—</strong><span>Mobile engagement</span><small>Verified data pending</small></article><article data-case-reveal><strong>—</strong><span>Core Web Vitals</span><small>Verified data pending</small></article></div></div></section>

    <section class="at-immersive section-space" aria-labelledby="at-immersive-title"><div class="site-container"><div class="at-immersive-copy" data-case-reveal><p class="eyebrow">Full website showcase</p><h2 id="at-immersive-title">One connected experience, from capability to contact.</h2></div><div class="at-immersive-stage" data-case-reveal><div class="at-browser tall"><div class="at-browser-bar"><i></i><i></i><i></i><span>actiontowingservice.ca</span></div><div class="at-immersive-hero"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-logo.svg' ) . '' ); ?>" alt=""><strong>24/7 towing across Edmonton</strong><span>Standard · Heavy duty · Commercial · Roadside</span></div><div class="at-immersive-grid"><div><small>01</small><b>Choose a service</b></div><div><small>02</small><b>Share your location</b></div><div><small>03</small><b>Dispatch the right truck</b></div></div><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-hero.webp' ) . '' ); ?>" loading="lazy" alt="Action Towing fleet"></div><div class="at-phone immersive"><div class="at-phone-top"></div><div class="at-phone-screen services"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/action-towing-logo.svg' ) . '' ); ?>" alt=""><small>24/7 SUPPORT</small><strong>Get help now.</strong><b>Call Action Towing</b><span>Roadside assistance</span><span>Vehicle recovery</span></div></div></div></div></section>

    <section class="at-outcomes section-space" aria-labelledby="at-outcomes-title"><div class="site-container"><div class="at-centered-intro" data-case-reveal><p class="eyebrow">Key improvements</p><h2 id="at-outcomes-title">A clearer foundation for every service journey.</h2></div><div class="at-outcome-grid"><article data-case-reveal><span>01</span><h3>Improved service navigation</h3><p>A broad catalogue is grouped into clear, recognizable routes.</p></article><article data-case-reveal><span>02</span><h3>Better mobile experience</h3><p>Contact actions and service choices stay easy to reach on smaller screens.</p></article><article data-case-reveal><span>03</span><h3>Stronger conversion paths</h3><p>Phone and request actions remain visible through high-intent moments.</p></article><article data-case-reveal><span>04</span><h3>Scalable content structure</h3><p>Service and location content can expand without weakening the hierarchy.</p></article></div></div></section>

    <section class="at-next section-space" aria-labelledby="at-next-title"><div class="site-container"><div class="at-next-shell" data-case-reveal><div><p class="eyebrow">Continue exploring</p><h2 id="at-next-title">Next case study</h2><h3>AKRoN Roofing</h3><p>A premium roofing brand positioned for a more specific market.</p><a class="button button-primary" href="https://www.reachfirst.com/case-studies/akron-roofing/">View case study<svg class="icon"><use href="#c-arrow-up"/></svg></a></div><a class="at-all-cases" href="<?php echo esc_url( reachfirst_page_url( 'case-studies' ) . '' ); ?>">All case studies <svg><use href="#c-arrow"/></svg></a></div></div></section>
    <section class="about-cta section-space"><div class="site-container"><div class="about-cta-panel"><div><p class="eyebrow">Start with a conversation</p><h2>What would you like to automate?</h2><p>Tell us where work is getting stuck. We&rsquo;ll help identify a practical next step.</p></div><a class="button about-cta-button" href="<?php echo esc_url( reachfirst_page_url( 'book-consultation' ) . '' ); ?>">Book AI Consultation<svg class="icon"><use href="#c-arrow-up"/></svg></a></div></div></section>
  </main>
<?php get_footer(); ?>
