<?php
/**
 * Template Name: Reach First — book consultation
 */
defined( 'ABSPATH' ) || exit;
get_header();
?>
<main id="main-content" tabindex="-1">
    <section class="consultation-hero section-space" aria-labelledby="consultation-page-heading"><div class="site-container consultation-hero-grid">
      <div class="consultation-hero-copy"><p class="eyebrow">Start with a conversation</p><h1 id="consultation-page-heading">Tell us what you would like to <span>make simpler.</span></h1><p>Share the process, system, or customer experience you want to improve. We’ll review the context and help determine whether automation, integration, or another practical next step makes sense.</p>
        <ul class="consultation-benefits" aria-label="What to expect"><li><span><svg aria-hidden="true"><use href="#rf-icon-check"></use></svg></span><div><strong>Start with the work</strong><small>No technical specification required.</small></div></li><li><span><svg aria-hidden="true"><use href="#rf-icon-check"></use></svg></span><div><strong>Talk through the systems</strong><small>We’ll consider the tools and handoffs already involved.</small></div></li><li><span><svg aria-hidden="true"><use href="#rf-icon-check"></use></svg></span><div><strong>Leave with a clearer next step</strong><small>Even when automation is not the right answer.</small></div></li></ul>
        <div class="consultation-direct" aria-label="Direct contact options"><p>Prefer to contact us directly?</p><a href="tel:+18447773224"><svg aria-hidden="true"><use href="#rf-icon-phone"></use></svg>1-844-777-3224</a><a href="mailto:info@reachfirst.com"><svg aria-hidden="true"><use href="#rf-icon-mail"></use></svg>info@reachfirst.com</a></div>
      </div>
      <div class="consultation-form-card" id="consultation-form"><div class="consultation-form-heading"><span aria-hidden="true"><svg><use href="#rf-icon-message"></use></svg></span><div><p>Request a consultation by email</p><h2>Tell us a little about the work.</h2></div></div><p class="consultation-email-explanation" id="consultation-email-explanation">This form prepares an email draft; it does not send a request or book a time. Review the draft, open it in your email app, and send it to info@reachfirst.com. If no email app opens, copy the draft into your preferred email service.</p><p class="consultation-form-intro">Fields marked <span aria-hidden="true">*</span><span class="sr-only">with an asterisk</span> are required.</p>
        <form class="consultation-request-form" aria-describedby="consultation-email-explanation" action="mailto:info@reachfirst.com?subject=Reach%20First%20consultation%20request" method="post" enctype="text/plain">
          <div class="consultation-field"><label for="consultation-name">Name <span aria-hidden="true">*</span></label><input id="consultation-name" name="Name" type="text" autocomplete="name" required></div>
          <div class="consultation-field"><label for="consultation-email">Work email <span aria-hidden="true">*</span></label><input id="consultation-email" name="Email" type="email" autocomplete="email" inputmode="email" required></div>
          <div class="consultation-field"><label for="consultation-company">Company <span aria-hidden="true">*</span></label><input id="consultation-company" name="Company" type="text" autocomplete="organization" required></div>
          <div class="consultation-field"><label for="consultation-phone">Phone <span>Optional</span></label><input id="consultation-phone" name="Phone" type="tel" autocomplete="tel" inputmode="tel"></div>
          <div class="consultation-field"><label for="consultation-interest">What would you like to discuss? <span>Optional</span></label><select id="consultation-interest" name="Area of interest"><option value="">Choose an area</option><option>AI consulting and automation planning</option><option>Business workflow automation</option><option>Sales and CRM automation</option><option>AI agents and customer support</option><option>AI voice agents</option><option>Custom applications and integrations</option><option>Managed automation support</option><option>Digital marketing services</option><option>Not sure yet</option></select></div>
          <div class="consultation-field"><label for="consultation-message">What process or problem would you like to improve? <span aria-hidden="true">*</span></label><textarea id="consultation-message" name="Project context" rows="5" required aria-describedby="consultation-message-help"></textarea><small id="consultation-message-help">A short description is enough. Please do not include passwords or sensitive customer information.</small></div>
          <button class="button button-primary consultation-submit" type="submit">Prepare consultation email<svg class="icon" aria-hidden="true"><use href="#rf-icon-arrow-up-right"></use></svg></button>
          <p class="consultation-form-note"><svg aria-hidden="true"><use href="#rf-icon-mail"></use></svg><span>Review the prepared draft below, then open it in your email app and send it. You can also email info@reachfirst.com directly.</span></p><noscript><p>With JavaScript disabled, this button opens your email app directly. Review the details and send the draft there, or email info@reachfirst.com.</p></noscript>
        </form><section class="consultation-draft" data-consultation-draft hidden aria-labelledby="consultation-draft-heading"><h3 id="consultation-draft-heading">Review your email draft</h3><p>To: info@reachfirst.com<br>Subject: Reach First consultation request</p><label for="consultation-draft-body">Prepared message</label><textarea id="consultation-draft-body" rows="9" readonly></textarea><a class="button button-primary" data-consultation-open href="mailto:info@reachfirst.com">Open draft in your email app</a><p>You must send the draft from your email app. No request has been sent or appointment booked.</p></section><p class="consultation-draft-status" role="status" aria-live="polite" data-consultation-status></p>
      </div>
    </div></section>

    <section class="consultation-context" aria-label="Consultation context"><div class="site-container consultation-context-grid"><p><strong>Based in Edmonton</strong><span>Serving businesses across Canada and the United States.</span></p><p><strong>Practical first conversation</strong><span>Bring the workflow, not a finished solution.</span></p><p><strong>People stay involved</strong><span>Review points and responsibilities remain part of the discussion.</span></p></div></section>

    <section class="consultation-next section-space" aria-labelledby="consultation-next-heading"><div class="site-container"><div class="consultation-section-intro"><p class="eyebrow">What happens next</p><h2 id="consultation-next-heading">After you send your email</h2><p>Once your email reaches us, we can review the context and arrange a suitable time to talk.</p></div><ol class="consultation-next-grid"><li><span>01</span><div class="consultation-step-icon" aria-hidden="true"><svg><use href="#rf-icon-message"></use></svg></div><h3>We review the context</h3><p>We look at the workflow, systems, and outcome described in your request.</p></li><li><span>02</span><div class="consultation-step-icon" aria-hidden="true"><svg><use href="#rf-icon-workflow"></use></svg></div><h3>We arrange a conversation</h3><p>We’ll confirm a suitable time and the people who should be involved.</p></li><li><span>03</span><div class="consultation-step-icon" aria-hidden="true"><svg><use href="#rf-icon-arrow-right"></use></svg></div><h3>We clarify the next step</h3><p>That may be a focused assessment, a defined pilot, or simply a clearer direction.</p></li></ol></div></section>

    <section class="consultation-faq section-space" aria-labelledby="consultation-faq-heading"><div class="site-container consultation-faq-layout"><div><p class="eyebrow">Before we talk</p><h2 id="consultation-faq-heading">A few practical details.</h2><p>You do not need a technical brief or a fully defined project to begin.</p></div><div class="services-faq-list"><details open><summary>What should I prepare?<svg aria-hidden="true"><use href="#rf-icon-chevron-down"></use></svg></summary><p>A real example of the process, the people involved, the systems used, and the point where work slows down or gets repeated.</p></details><details><summary>Can we start if we are not sure which service we need?<svg aria-hidden="true"><use href="#rf-icon-chevron-down"></use></svg></summary><p>Yes. Start with the business problem. We can use the conversation to determine which capability, if any, is relevant.</p></details><details><summary>Can you work with our existing software?<svg aria-hidden="true"><use href="#rf-icon-chevron-down"></use></svg></summary><p>Often, but it depends on the system’s available connections, permissions, data structure, and the requirements of the workflow.</p></details><details><summary>Where does Reach First work?<svg aria-hidden="true"><use href="#rf-icon-chevron-down"></use></svg></summary><p>Reach First is based in Edmonton and works with service businesses across Canada and the United States.</p></details></div></div></section>
  </main>
<?php get_footer(); ?>
